### ISSUE TITLE
GH workflow builds against ngen submodule commit, not current commit

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/noah-owp-modular#104]
https://github.com/NOAA-OWP/noah-owp-modular/blob/05aec159a872fe4ba5b6a490c4ed91878b2396cb/.github/workflows/ngen_integration.yaml#L95

Just noticed that the workflow here is using the ngen build-submodule action to build the NOM library to test the integration with.  This will cause the runner to use the pinned ngen submodule commit to build form, not the current code.  This likely isn't the intended behavior here.

Can either toy with the ngen submod build action to try to get the correct code/pr-branch updated in the runner's ngen clone, or simply build the ngen lib from source (would be easier once #103 is complete).  Could also hack somewhere in the middle and use the checked out code to overwrite the dir and try to re-build via a second action step.

Either way, something to think about for getting a local integration test setup.

**Comment by madMatchstick** [comment]
> @hellkite500, other ngen-build workflows are failing (e.g., in [evapotranspiration](https://github.com/NOAA-OWP/evapotranspiration/actions/runs/8299846846/job/22716483404?pr=31)). Do you think this is the cause across formulations?

So, there's kind of two unique-ish things going on here, 
1. This issue Nels just outline.  Most (if not all?) `ngen_integration.yml` workflows (across all implemented formation repos) directly call an existing 'ngen' [action](https://github.com/NOAA-OWP/ngen/blob/master/.github/actions/ngen-submod-build/action.yaml) to build (sub)module libraries.  Although convenient because the set-up already exists, this is not exactly what we want because action pulls whatever pinned commit is currently in `ngen/extern` from the submodules   `master`/`main` branch.  So we aren't even running the integration workflow with updated code from PR.   At glance, I'm thinking `${{ github.head_ref }}` maybe worth investigating...
2. Because the NOM [build](https://github.com/NOAA-OWP/ngen/blob/f91e2ea9dbce706a2faa6f04d0600c2522db6006/extern/noah-owp-modular/CMakeLists.txt#L30) requires a  `-DNGEN_IS_MAIN_PROJECT` flag, the use of the linked action in (1) to build NOM specifically, now breaks as `ngen` issue [#761](NGEN_IS_MAIN_PROJECT) addresses.  See proposed `ngen` pr [#768](https://github.com/NOAA-OWP/ngen/pull/768) if this helps clarify. 

@hellkite500 can correct me if I'm off.  I believe getting item (1), this issue #104, is more priority.

**Comment by stcui007** [comment]
It looked like this line of codes in ngen-submodule-build/action.yaml:
          run: git submodule update --init --recursive -- ${{
inputs.mod-dir }}
over wrote the newest version we checked out earlier and moved back to
extern/. We should build the submodule before checkout ngen and move the
already built sub-module to extern, not build using ngen submodule action.

**Comment by stcui007** [comment]
Looks like this is not an across all submodule problem for
workflows/ngen-integration. But, at least another one, Topmodel, possibly
PET, may need to be fixed.

**Comment by madMatchstick** [comment]
ok, I'll take a look. Thanks @stcui007 !
