### ISSUE TITLE
Build error on GNU fortran 12.2.0

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/noah-owp-modular#68]
With the following cmake configuration:
```sh
$ cmake ..
-- The Fortran compiler identification is GNU 12.2.0
-- Checking whether Fortran compiler has -isysroot
-- Checking whether Fortran compiler has -isysroot - yes
-- Checking whether Fortran compiler supports OSX deployment target flag
-- Checking whether Fortran compiler supports OSX deployment target flag - yes
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: gfortran - skipped
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: cmake_build
```
I get the following build error when running `make` in the build directory:
```sh
noah-owp-modular/src/DomainType.f90:110:48:

  110 |     this%terrain_slope  = namelist%terrain_slope
      |                                                1
Error: 'terrain_slope' at (1) is not a member of the 'namelist_type' structure
noah-owp-modular/src/DomainType.f90:111:42:

  111 |     this%azimuth        = namelist%azimuth
      |                                          1
Error: 'azimuth' at (1) is not a member of the 'namelist_type' structure
```

**Comment by andywood** [comment]
It's an easy quick fix to update the namelist structure code to have these parameters, but I think they are more appropriate as input attributes rather than namelist entries.  We don't have a dedicated attributes input file (eg geophysical attributes rather than process parameters), and it could go into one of the parameters files, either MPTABLE.TBL or GENPARM.TBL.  

This too is not really what we want however -- we should consider adding functionality here.  These attributes vary by location.  I think we do not want an individual namelist file or any of the 3 major param files duplicated for every single catchment, versus a 'LOCPARM' file that can have a mixture of local attributes and parameters.   

Right now we have either global parameters (in either namelist or GENPARM) or library parameters (for soil types/veg types) in the other two param files (VEGPARM and MPTABLE).  The distributed/local parameters & attributes have no way to be input, and it would be good to address this.  The time for the distributed driver or related functionality may be upon us.

**Comment by hellkite500** [comment]
So the build error here was something strange hanging around the repository after a git update.  I ended up nuking the repo and re-initializing it and this build error went away.  Though I would have expected that the fresh cmake build directory should have been sufficient, but apparently not...
