### ISSUE TITLE
New `IMPERV_OPTION` added to `nwm 3.0.6`?

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/noah-owp-modular#93]
I noticed `nwm 3.0.6` appears to have [added](https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/nwm.v3.0.6/parm/analysis_assim/namelist.hrldas) an `IMPERV_OPTION` to the NoahLSM version being used. Im not familiar with these changes, but I was curious if there are plans to mirror the new functionality in `noah-owp-modular`?

See the `IMPERV_OPTION` under the `NOAHLSM_OFFLINE` section of in the `namelist.hrldas` file:

```namelist
IMPERV_OPTION                     = 2  !(0->none; 1->total; 2->Alley&Veenhuis; 9->orig)
```

**Comment by SnowHydrology** [comment]
@aaraney, thanks for bringing this to our attention. A comment and a question:

- We don't typically deploy any of the infiltration-runoff partitioning schemes in Noah-OWP-Modular because NextGen usually uses Noah-OM in surface mode. (So we probably won't implement the change.)
- Can you point to where in the WRF-Hydro/Noah-MP source code this change is implemented?

**Comment by SnowHydrology** [comment]
Closing this issue because, as of this time, Noah-OWP-Modular will be run in surface mode and won't handle infiltration-runoff partitioning. See [related capability](https://github.com/NOAA-OWP/cfe/blob/041c11c4eeab23cd002d86f37a75f129c7a7583f/src/cfe.c#L522) in CFE.
